import { TIME_PERIODS, type TTimePeriod } from "./types";

export const TIME_PERIOD_PRESETS: TTimePeriod[] = [
  TIME_PERIODS.THIS_MONTH,
  TIME_PERIODS.LAST_MONTH,
  TIME_PERIODS.THIS_YEAR,
  TIME_PERIODS.LAST_6_MONTHS,
  TIME_PERIODS.LAST_12_MONTHS,
];
